# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

### test
POST http://{{hostname}}/tdsms-web-service/queryTerminals
Content-Type: application/x-www-form-urlencoded

username={{username}}&ruleId={{ruleId}}&size=20&sign={{sign}}
###
GET http://{{hostname}}/tdsms-web-service/queryAllRules

###